apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain
  namespace: rental-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
      - name: blockchain
        image: abde142/blockchain:latest
        ports:
        - containerPort: 8545
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain
  namespace: rental-app
spec:
  selector:
    app: blockchain
  ports:
  - port: 8545
    targetPort: 8545
  type: ClusterIP